services:
  kibana:
    depends_on:
      es01:
        condition: service_healthy
      es02:
        condition: service_healthy
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    volumes:
      - ./config:/usr/share/kibana/config
      - ${KIBANA_STORAGE}:/usr/share/kibana/data
    user: "kibana:kibana"
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      SERVER_PUBLICBASEURL: https://crunchy.dyndns.org/kibana
      SERVER_NAME: kibana # defaults to 'your-hostname'
      SERVER_HOST: 0.0.0.0
      SERVER_BASEPATH: /kibana
      SERVER_REWRITEBASEPATH: false
      XPACK_SECURITY_ENABLED: false
      XPACK_SECURITY_ENROLLMENT_ENABLED: true
      # XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: 4cc57790c6dd1e707a3993cbc88c59c5
      # XPACK_REPORTING_ENCRYPTIONKEY: b755ef12860b8fb1fca351512f662fd5
      # XPACK_SECURITY_ENCRYPTIONKEY: 1cf6bdcfe739eac8da4479d9f46b325e
    mem_limit: ${MEM_LIMIT}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    networks:
      - homeserver
    profiles:
      - llm
      - elastic
    container_name: kibana