GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA bantam TO idst_api_read;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA bantam TO idst_api_read;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA bantam TO idst_api_read;
ALTER ROLE idst_api_read SUPERUSER CREATEDB	CREATEROLE;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA bantam TO idst_data_ingest;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA bantam TO idst_data_ingest;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA bantam TO idst_data_ingest;
ALTER ROLE idst_data_ingest SUPERUSER CREATEDB	CREATEROLE;